### ISSUE TITLE
all.sql schemaObject Order Changes

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#509] opened 2016-09-02 05:18 UTC
We are committing the all.sql to our repo to assist with our Database team in approving DDL scripts.  For testing purposes, they like to be able to run the all.sql that is generated by Marten's `WriteDDLByType` method.

Everytime this method is invoked and the `all.sql` file is created, it doesn't keep the order of the `\i schemaObject.sql`.

> Can a `order by name` be added to the forEach that is generating these lines to keep their output consistent?

In `DocumentSchema.cs`, method `writeDatabaseSchemaGenerationScript()`.

**Comment by bradyclifford** [comment] 2016-09-02 05:18
Low priority

**Comment by jeremydmiller** [comment] 2016-09-06 20:01
@bradyclifford I did *some* sorting to at least make it reproducible. However, the document scripts have to be done w/ a topological sort because of the foreign keys between document types. Same thing w/ sticking the functions first.

**Comment by jeremydmiller** [comment] 2016-09-06 20:05
Fixed by https://github.com/JasperFx/marten/commit/749503f69feb03cc0377a027316b5cd4c0f1b96b

**Closed by jeremydmiller** 2016-09-06 20:05 UTC
