### ISSUE TITLE
Indexes on DateTime properties get dropped and recreated every time schema is applied

### ISSUE THREAD

**Issue by mfuqua3** [JasperFx/marten#2652] opened 2023-07-18 22:04 UTC
Verified against Marten v6.0.4

```csharp
public class ApiResponseRecord
{
    public Guid Id { get; set; }
    public string Request { get; set; }
    public string Response { get; set; }
    public DateTime RequestTimeUtc { get; set; }
}
```

```csharp
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        /* service configuration calls */
        services.AddMarten((provider) =>
            {
                var postgresOptions = provider.GetRequiredService<IOptions<PostgresOptions>>().Value;
                var storeOptions = new StoreOptions
                {
                    AutoCreateSchemaObjects = AutoCreate.All,
                };
                storeOptions.Schema.For<ApiResponseRecord>().Index(x => x.RequestTimeUtc);
                storeOptions.Connection(postgresOptions.ConnectionString);
                return storeOptions;
            })
            .ApplyAllDatabaseChangesOnStartup();
    }
}
```

With a configuration like the one above, the following sql will execute each time the app starts:

```sql
drop index if exists public.mt_doc_apiresponserecord_idx_request_time_utc;
CREATE INDEX mt_doc_apiresponserecord_idx_request_time_utc ON public.mt_doc_apiresponserecord USING btree ((public.mt_immutable_timestamp(data ->> 'RequestTimeUtc')));
```

**Expected Result** - Index gets applied if it does not exist, no action if it exists already
**Actual Result** - Index gets dropped and created each time regardless of database state

**Comment by oskardudycz** [comment] 2023-07-22 08:46
@mfuqua3 I tried to reproduce your scenario in https://github.com/JasperFx/marten/pull/2655/files#diff-0c8555b4b4b3ed2b6ea1110ea109c61dd10d187f78510373f32480851d698948R185. But it seems to be working fine.

Is the config you provided the complete one?

Could you add more reproduction steps or a sample project that I could debug?

**Comment by mfuqua3** [comment] 2023-07-22 13:09
It is not the complete config I'm using, I scaled it down for simplicity. I'll investigate this further and add new repro steps.

**Comment by oskardudycz** [comment] 2023-07-22 13:13
Thanks, that looks like some edge case, so repro steps would be great. Also Postgres version and config if it's unusual.

**Comment by oskardudycz** [comment] 2023-07-23 13:28
@michaldog, FTS delta calculation was fixed in https://github.com/JasperFx/marten/pull/2655

**Comment by oskardudycz** [comment] 2023-07-24 11:49
@mfuqua3, I'm going to close the issue for now, but if you manage to send us reproduction steps, I'll reopen it.

**Closed by oskardudycz** 2023-07-24 11:49 UTC
Labels: bug, schema management, full text search, 6.x
