### ISSUE TITLE
Marten 7: Command Failure (0x80004005): 42P01: relation "mt_temp_id_list1" does not exist

### ISSUE THREAD

**Issue by TatChu** [JasperFx/marten#3082] opened 2024-03-24 15:05 UTC
Code snippet:
```csharp
User? user = null;
BusinessFields? businessField = null;
var userEducation = await _session
        .Query<UserEducation>()
        .Include<User>(x => x.UserId, u => user = u)
        .Include<BusinessFields>(x => x.EducationFieldId, bf => businessField = bf)
        .Where(p => p.Id == request.Id)
        .FirstAsync(cancellationToken);

public class UserEducation
{
    public string Id{ get; set; }
    public string EducationFieldId { get; set; }
    public string UserId { get; set; }
}

public class User
{
    public string Id { get; set; }
    public string Name { get; set; }
}
public class BusinessFields
{
    public string Id { get; set; }
    public string Name { get; set; }
}
```
Issue observed: It can run successfully the first time, but then encounters an issue from the second time onwards.
Context: marten 7.4.0
Details exception:
```
Marten.Exceptions.MartenCommandException: Marten Command Failure:$
$
$
42P01: relation "mt_temp_id_list1" does not exist

POSITION: 92
 ---> Npgsql.PostgresException (0x80004005): 42P01: relation "mt_temp_id_list1" does not exist

POSITION: 92
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteReaderAsync(NpgsqlBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteReaderAsync(NpgsqlBatch batch, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "mt_temp_id_list1" does not exist
    Position: 92
    File: parse_relation.c
    Line: 1194
    Routine: parserOpenTable
   --- End of inner exception stack trace ---
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Linq.MartenLinqQueryable`1.ToListAsync[TResult](CancellationToken token)
```

**Comment by jeremydmiller** [comment] 2024-03-26 12:35
@TatChu And you get the dreaded "works on my box"

Here's the test I used:

```csharp
public class Bug_3082_trouble_with_repeated_include_usage : BugIntegrationContext
{
    [Fact]
    public async Task query_multiple_times()
    {
        await executeQuery();
        await executeQuery();
    }

    private async Task executeQuery()
    {
        User3082 user = null;
        BusinessFields businessField = null;
        var userEducation = await theSession
            .Query<UserEducation>()
            .Include<User3082>(x => x.UserId, u => user = u)
            .Include<BusinessFields>(x => x.EducationFieldId, bf => businessField = bf)
            .FirstOrDefaultAsync(x => x.Id == Guid.NewGuid().ToString());
    }
}

public class UserEducation
{
    public string Id{ get; set; }
    public string EducationFieldId { get; set; }
    public string UserId { get; set; }
}

public class User3082
{
    public string Id { get; set; }
    public string Name { get; set; }
}
public class BusinessFields
{
    public string Id { get; set; }
    public string Name { get; set; }
}

```

What version of Marten are you using? I'll try again w/ the "sticky" connection approach and see if that makes a difference

**Comment by jeremydmiller** [comment] 2024-03-26 12:36
And nope, that passes too. I'm closing this for now when that test is in. Let me know if there's any other reproduction step I'm missing. And if you haven't already, I'd be curious how 7.* does with this.

**Closed** 2024-03-26 13:32 UTC

**Comment by louisfeutrie** [comment] 2024-03-28 10:57
Hi @jeremydmiller, I have the same problem as TatChu.
.net 8 with marten 7.4
to reproduce it with the minimun requirement, i just need to do 2 same query with include on the same session.

for example:
`    
            var stockItems = await session.Query<StockItem>()
                                          .Include(si => si.SparePartId, spareParts)
                                          .ToListAsync(cancellationToken);

            stockItems = await session.Query<StockItem>()
                                          .Include(si => si.SparePartId, spareParts)
                                          .ToListAsync(cancellationToken);
`

**Comment by ben-wallis** [comment] 2024-03-28 15:42
I've also come across this bug with a similar `.Include()` statement to the one shown above in Marten 7.5.0 - we were only using a single instance of `Include()` in the codebase though so it was easy to refactor to avoid its usage.

**Comment by PNZeml** [comment] 2024-04-16 05:29
Hello. I have same exception with 7.4+ version of Marten.

```csharp
InputSource? inputSource = null;

var device = await session.Query<Device>()
    .Include<InputSource>(x => x.InputSourceId, x => inputSource = x)
    .SingleOrDefaultAsync(x => x.Id == req.DeviceId, c);
```

Logs
```
[12:08:29 DBG] Executing batch: ["drop table if exists mt_temp_id_list1", "create temp table mt_temp_id_list1 as (select d.data, d.input_source_id from mt_temp_id_list1 as d where d.id = $1);", " select d.data from kop_soyuz.mt_doc_input_sources as d where d.id in (select d.input_source_id from mt_temp_id_list1 as d)", " select d.data, d.input_source_id from mt_temp_id_list1 as d"]
[12:08:29 DBG] Received notice: table "mt_temp_id_list1" does not exist, skipping
[12:08:29 VRB] Cleaning up reader
[12:08:29 INF] Batch execution completed (duration=23ms): ["drop table if exists mt_temp_id_list1", "create temp table mt_temp_id_list1 as (select d.data, d.input_source_id from mt_temp_id_list1 as d where d.id = $1);", " select d.data from kop_soyuz.mt_doc_input_sources as d where d.id in (select d.input_source_id from mt_temp_id_list1 as d)", " select d.data, d.input_source_id from mt_temp_id_list1 as d"]
```
Generated SQL on 7.7.0 has issue on the second CREATE statement. It says `d.id` does not exists.
```sql
drop table if exists mt_temp_id_list1;
create temp table mt_temp_id_list1 as (select d.data, d.input_source_id from mt_temp_id_list1 as d where d.id = 1);
select d.data from kop_soyuz.mt_doc_input_sources as d where d.id in (select d.input_source_id from mt_temp_id_list1 as d);
select d.data, d.input_source_id from mt_temp_id_list1 as d;
```

On 7.3.0 this query batch looks like this:
```sql
drop table if exists mt_temp_id_list1;
create temp table mt_temp_id_list1 as (select d.data, d.input_source_id from kop_soyuz.mt_doc_devices as d where d.id = 1);
select d.data from kop_soyuz.mt_doc_input_sources as d where d.id in (select d.input_source_id from mt_temp_id_list1 as d);
select d.data, d.input_source_id from kop_soyuz.mt_doc_devices as d;
```
