### ISSUE TITLE
`Contains` query intermittently failing with `NotSupportedException`

### ISSUE THREAD

**Issue by pip36** [JasperFx/marten#2698] opened 2023-09-01 14:18 UTC
**Marten Version:**  5.11.0

I've been seeing intermittent `NotSupportedExceptions` being thrown by Marten when using `.Contains` in a query. After some digging it appears that marten is caching the `IMethodCallParser` after first lookup.
https://github.com/JasperFx/marten/blob/3ac2692d07f637ee7ab597610df9b33fb754aabc/src/Marten/LinqParsing.cs#L128

The error is thrown reliably in either the `EnumerableContains` or `IsInGenericEnumerable` IMethodCallParser. I can reproduce the issue in a test below. If you comment out either one of the queries then no exception is thrown, and the queries run as expected. But when run together in the same test the second query will fail with a `NotSupportedException` due to finding the wrong parser.

```c#
[Fact]
public void Test_Throws_NotSupportedException()
{
    var store = DocumentStore.For(
        x =>
            {
                x.Connection("connection_string");
                x.DatabaseSchemaName = "testschema";
            });

    using var session = store.OpenSession();
   
    // EnumerableContains
    var query = session.Query<TestModel>().FirstOrDefault(x => x.Ids.Contains(Guid.Empty));

    // IsInGenericEnumerable
    var query2 = session.Query<TestModel>().FirstOrDefault(x => new List<Guid> { Guid.Empty }.Contains(x.Id));
}

public class TestModel
{
    public Guid Id { get; set; }

    public List<Guid> Ids { get; set; } = new List<Guid>();
}
```

**Comment by Hawxy** [comment] 2023-09-04 09:38
Same issue as in #2452.

**Comment by jeremydmiller** [comment] 2023-09-09 15:32
I've got this. I might know what the root cause is, and it's already fixed on the "linq" branch. Same little fix will work here too.

**Comment by jeremydmiller** [comment] 2023-11-24 22:25
This is actually beaten in V7 now.

**Closed by jeremydmiller** 2023-11-24 22:25 UTC
Labels: linq
