### ISSUE TITLE
Exception thrown if multiple event streams are created in same session in Marten v4 alpha 6

### ISSUE THREAD

**Issue by VilleHakli** [JasperFx/marten#1754] opened 2021-03-09 09:39 UTC
If multiple event streams are created in single session, exception is thrown about foreign key constrain violation when saving changes:
```
Marten.Exceptions.MartenCommandException: Marten Command Failure:$
insert into bugs.mt_streams (id, type, version, tenant_id) values (:p0, :p1, :p2, :p3); [multiple insert/delete statements removed]
$
23503: insert or update on table "mt_events" violates foreign key constraint "mt_events_stream_id_fkey"
 ---> Npgsql.PostgresException (0x80004005): 23503: insert or update on table "mt_events" violates foreign key constraint "mt_events_stream_id_fkey"
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marten.NulloRetryPolicy.Execute[TResult](Func`1 operation) in C:\marten\src\Marten\NulloRetryPolicy.cs:line 19
   at Marten.Services.ManagedConnection.ExecuteReader(NpgsqlCommand command) in C:\marten\src\Marten\Services\ManagedConnection.cs:line 261
  Exception data:
    Severity: ERROR
    SqlState: 23503
    MessageText: insert or update on table "mt_events" violates foreign key constraint "mt_events_stream_id_fkey"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: bugs
    TableName: mt_events
    ConstraintName: mt_events_stream_id_fkey
    File: ri_triggers.c
    Line: 2783
    Routine: ri_ReportViolation
   --- End of inner exception stack trace ---
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e) in C:\marten\src\Marten\Services\ManagedConnection.cs:line 227
   at Marten.Services.ManagedConnection.ExecuteReader(NpgsqlCommand command) in C:\marten\src\Marten\Services\ManagedConnection.cs:line 267
   at Marten.Internal.UpdateBatch.ApplyChanges(IMartenSession session) in C:\marten\src\Marten\Internal\UpdateBatch.cs:line 30
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatch(IUpdateBatch batch) in C:\marten\src\Marten\Internal\Sessions\DocumentSessionBase.SaveChanges.cs:line 44
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChanges() in C:\marten\src\Marten\Internal\Sessions\DocumentSessionBase.SaveChanges.cs:line 27
   at Marten.Testing.Events.Bugs.Bug_1754_multiple_event_streams_in_one_session_fails.should_be_able_to_handle_multiple_event_streams_in_one_session() in C:\marten\src\Marten.Testing\Events\Bugs\Bug_1754_multiple_event_streams_in_one_session_fails.cs:line 37
```

I did a little digging around and found out that:
- If there is limited number of streams created in one session this does not happen. In the test case below everything works if only two streams are created for DataItemAggregate
- If there are no projections configured no exception is thrown. Also if projections in the example below are configured with async lifecycle then saving of the streams also succeeds.
- The bug might be in the sorting logic of storage operations in ```UnitOfWork.Sort``` as removing call to it in ```DocumentSessionBase.SaveChanges``` "fixed" the issue.

Test case to reproduce the issue
```csharp
using System;

using Bug1754;

using Marten.Events.Projections;
using Marten.Testing.Harness;

using Shouldly;

using Xunit;

namespace Marten.Testing.Events.Bugs
{
    public class Bug_1754_multiple_event_streams_in_one_session_fails : BugIntegrationContext
    {
        [Fact]
        public void should_be_able_to_handle_multiple_event_streams_in_one_session()
        {
            using var documentStore = SeparateStore(x =>
            {
                x.Events.Projections.SelfAggregate<DataImportAggregate>(ProjectionLifecycle.Inline);
                x.Events.Projections.SelfAggregate<DataItemAggregate>(ProjectionLifecycle.Inline);
            });

            using var session = documentStore.OpenSession();

            var importStream = session.Events.StartStream<DataImportAggregate>(new DataImportStartedEvent {ByUser = Guid.NewGuid()});

            var importCount = 0;
            for (var i = 0; i < 10; i++)
            {
                session.Events.StartStream<DataItemAggregate>(new CreateDataItem {ImportId = importStream.Id, Name = $"Data item {i}"});
                ++importCount;
            }

            session.Events.Append(importStream.Id, new DataImportFinishedEvent {ImportCount = importCount});
            session.SaveChanges();

            using var querySession = documentStore.QuerySession();
            var importAggregate = querySession.Load<DataImportAggregate>(importStream.Id);
            importAggregate.ShouldNotBeNull();
            importAggregate.ImportCount.ShouldBe(importCount);
        }
    }
}

namespace Bug1754
{
    public class DataImportStartedEvent
    {
        public Guid ByUser { get; set; }
    }

    public class DataImportFinishedEvent
    {
        public int ImportCount { get; set; }
    }

    public class DataImportAggregate
    {
        public Guid Id { get; set; }

        public Guid StartedByUser { get; set; }
        public int ImportCount { get; set; }

        public void Apply(DataImportStartedEvent started) => StartedByUser = started.ByUser;

        public void Apply(DataImportFinishedEvent finished) => ImportCount = finished.ImportCount;
    }

    public class CreateDataItem
    {
        public Guid ImportId { get; set; }
        public string Name { get; set; }
    }

    public class DataItemAggregate
    {
        public Guid Id { get; set; }

        public Guid ImportId { get; set; }
        public string Name { get; set; }

        public void Apply(CreateDataItem dataItem)
        {
            ImportId = dataItem.ImportId;
            Name = dataItem.Name;
        }
    }
}
```

**Comment by jeremydmiller** [comment] 2021-03-09 13:43
@VilleHakli I saw this a little bit in development, but then couldn't reproduce it and wrote it off. I'll take a look. No ideas yet, but that code is pretty simplistic.

Thank you for the very good bug reports with the reproduction tests, that's very helpful.

**Comment by jeremydmiller** [comment] 2021-03-10 16:44
Fix is in my next push.

**Closed** 2021-03-11 21:18 UTC
Labels: bug
