### ISSUE TITLE
Timeout while getting a connection from pool when using isoneof in asp.net API

### ISSUE THREAD

**Issue by jefjef** [JasperFx/marten#294] opened 2016-04-14 15:24 UTC
When calling a query with marten that uses **IsOneOf** in a web api call the connection never gets closed, and when the 21's call (with a pool size of 20)  happens an error gets thrown: Timeout while getting a connection from pool. 

![devenv_2016-04-14_17-22-22](https://cloud.githubusercontent.com/assets/254635/14533467/7dadc448-0265-11e6-9a86-5798862647a2.png)

When i look in at the server status in pg admin i do see all the open but idle connections that are supposed to be reused. 

![pgadmin3_2016-04-14_17-04-01](https://cloud.githubusercontent.com/assets/254635/14533401/3c06f906-0265-11e6-9d59-e34c2d87ec0e.png)

It seems to only happen when using an API, possibly because every call is async?

Example [here](https://github.com/jefjef/MartenIsOneOfIssue)

**Comment by jeremydmiller** [comment] 2016-04-14 15:27
@jefjef Are you disposing the sessions after your done with them? When we went to the "sticky connection" thing, you now have to dispose the `IQuerySession` or `IDocumentSession`.

**Comment by jefjef** [comment] 2016-04-15 06:33
we use sessions in a using statement, that should be enough right?

**Comment by jeremydmiller** [comment] 2016-04-15 10:59
@jefjef From glancing at your code, yes. I'll take a look at this this afternoon and see if I can reproduce what you're seeing. I don't really have any explanation yet.

**Comment by jeremydmiller** [comment] 2016-04-15 12:41
@jefjef Hey, if you're using Postgresql 9.5, can you try again w/ `UpsertStyle = UpsertStyle.Standard` to opt into the more efficient upsert mechanism? Another user is telling me today that he saw connection timeouts in stress testing that go away when you opt into the 9.5 style.

**Comment by nieve** [comment] 2016-04-15 12:46
@jeremydmiller His issue is due to queries rather than upserts.

**Comment by jefjef** [comment] 2016-04-15 12:48
Yes, its only when i use a query that uses IsOneOf, session.Load and session.Store work fine

**Comment by jeremydmiller** [comment] 2016-04-15 12:57
Yeah, but I didn't know if it was because connections were getting soaked up in the SaveChanges() with requests running in parallel

**Comment by nieve** [comment] 2016-04-15 13:27
I can reproduce by running @jefjef code locally.

**Comment by jeremydmiller** [comment] 2016-04-15 13:34
Does it really go away if you replace IsOneOf() with maybe a (prop == 1 || prop == 2) kind of query? Just trying to see if it's really isolated to that one Linq handler

**Comment by nieve** [comment] 2016-04-15 13:36
Nope, it has nothing to do with IsOneOf.

**Comment by nieve** [comment] 2016-04-15 13:36
trying to get a test for it

**Comment by nieve** [comment] 2016-04-15 13:40
The following test fail (but passes when there's only one task running):
```csharp
        [Fact]
        public void concurrent()
        {
            theSession.Store(new Target { Color = Colors.Blue, Number = 1 });
            theSession.Store(new Target { Color = Colors.Red, Number = 2 });
            theSession.Store(new Target { Color = Colors.Green, Number = 3 });
            theSession.Store(new Target { Color = Colors.Blue, Number = 4 });

            theSession.SaveChanges();
            var ts = new List<Task<List<Target>>>();
            Enumerable.Range(0, 2)
                .ToList()
                .ForEach(_ => ts.Add(theSession.Query<Target>().Where(x => x.Number < 3).ToListAsync()));
            Task.WhenAll(ts).GetAwaiter().GetResult();
        }
```

**Comment by jeremydmiller** [comment] 2016-04-15 13:45
Are you hitting the exact same session every time?

**Comment by nieve** [comment] 2016-04-15 13:53
Nice one!
I got a proper failing test:
``` csharp
        [Fact]
        public void concurrent()
        {
            theSession.Store(new Target { Color = Colors.Blue, Number = 1 });
            theSession.Store(new Target { Color = Colors.Red, Number = 2 });
            theSession.Store(new Target { Color = Colors.Green, Number = 3 });
            theSession.Store(new Target { Color = Colors.Blue, Number = 4 });

            theSession.SaveChanges();
            var ts = new List<Task<List<Target>>>();
            var sessions = new List<IDocumentSession>();
            try
            {
                Enumerable.Range(0, 20)
                    .ToList()
                    .ForEach(_ =>
                    {
                        var session = theStore.LightweightSession();
                        sessions.Add(session);
                        ts.Add(session.Query<Target>().Where(x => x.Number == 3).ToListAsync());
                    });
                Task.WhenAll(ts).GetAwaiter().GetResult();
            }
            finally
            {
                sessions.ForEach(s=>s.Dispose());
            }
        }
```

And it passes with 19 tasks!

**Comment by jeremydmiller** [comment] 2016-04-15 13:55
20 is the default # of connections for Npgsql. Wanna jack that up to 50 and see if it breaks?

You aren't disposing the session, is that purposeful?

**Comment by nieve** [comment] 2016-04-15 13:56
Disposing them in the finally clause. will give 50 a go.

**Comment by nieve** [comment] 2016-04-15 14:11
Yup, 50 works like a charm and fails, as expected, when I up it to 50 sessions :smile:

**Comment by jeremydmiller** [comment] 2016-04-15 14:20
Any difference w/ the Dispose()?

**Comment by jeremydmiller** [comment] 2016-04-15 14:21
We *could* be more aggressive in shutting down the connection. Say if we were to immediately shut down the open connection right after SaveChanges() is called, then lazily open another connection if you need it later.

**Comment by nieve** [comment] 2016-04-15 14:30
Ok, so this is passing (as you suggested)
``` csharp
        [Fact]
        public void concurrent()
        {
            theSession.Store(new Target { Color = Colors.Blue, Number = 1 });
            theSession.Store(new Target { Color = Colors.Red, Number = 2 });
            theSession.Store(new Target { Color = Colors.Green, Number = 3 });
            theSession.Store(new Target { Color = Colors.Blue, Number = 4 });

            theSession.SaveChanges();
            theSession.Dispose();

            var ts = new List<Task>();Enumerable.Range(0, 100)
                .ToList()
                .ForEach(_ =>
                {
                    var session = theStore.LightweightSession();
                    ts.Add(session.Query<Target>().Where(x => x.Number == 3).ToListAsync().ContinueWith(t=>session.Dispose()));
                });
            Task.WhenAll(ts).GetAwaiter().GetResult();
        }
```

Is this something we will have to roll inside marten or rather set as a best practice? Inside marten I suppose isn't really an option.

**Comment by nieve** [comment] 2016-04-15 14:39
You mean disposing of IManagedConnection inside the session straight after executing any CRUD command/query, right?

**Comment by jeremydmiller** [comment] 2016-04-15 14:46
Yes, or at least having `IManagedConnection` reset itself so it's not hanging on to the connection any longer.

**Comment by jeremydmiller** [comment] 2016-04-15 14:47
I think it's a best practice, period. The docs to call that out.

**Comment by jefjef** [comment] 2016-04-15 14:57
I don't really understand this, we use a using statement with our sessions, so shouldn't the connection be released and added back to the pool when the using statement ends?

**Comment by jeremydmiller** [comment] 2016-04-15 16:19
@jefjef And that makes two of us. The connection *is* disposed when the `IQuerySession` or `IDocumentSession` is disposed, but we're not explicitly closing it. I didn't think that mattered, but I've been wrong before.

**Comment by nieve** [comment] 2016-04-15 20:05
Ok, I think I missed the whole thing. This is the real failing test:
``` csharp
        [Fact]
        public void concurrent()
        {
            theSession.Store(new Target { Color = Colors.Blue, Number = 1 });
            theSession.Store(new Target { Color = Colors.Red, Number = 2 });
            theSession.Store(new Target { Color = Colors.Green, Number = 3 });
            theSession.Store(new Target { Color = Colors.Blue, Number = 4 });

            theSession.SaveChanges();
            theSession.Dispose();

            var ts = new List<Task<IQueryable<Target>>>();
            Enumerable.Range(0, 142)
                .ToList()
                .ForEach(_ =>
                {
                    ts.Add(Task.Run(() =>
                    {
                        using (var session = theStore.LightweightSession())
                            return session.Query<Target>().Where(x => x.Number == 3);
                    }));
                });
            var targets = Task.WhenAll(ts).GetAwaiter().GetResult();
            targets.SelectMany(t=>t.ToArray()).Count().ShouldBe(142);
        }
```
since @jefjef was not calling ToList() after the Where() the sessions were all called roughly on the same time rather than query being executed and then session disposed.
This fixes it:
``` csharp
session.Query<Target>().Where(x => x.Number == 3).ToList();
```

**Comment by jefjef** [comment] 2016-04-15 20:26
Nice, that fixed it :smile:

**Comment by jeremydmiller** [comment] 2016-04-15 22:39
I'm going to go ahead and close this one. Thanks @nieve for running through this one.

**Closed by jeremydmiller** 2016-04-15 22:39 UTC

**Comment by jefjef** [comment] 2016-04-15 22:44
Yes, thanks guys :smiley:
