### ISSUE TITLE
Patch Method truncates long Id

### ISSUE THREAD

**Issue by kinl99** [JasperFx/marten#1315] opened 2019-07-16 06:25 UTC
When trying to patch an object with a long Id, the Id in the json data gets truncated:

(Postgres 11.1, PLV8 2.3.9, Docker, Marten 3.4.0 and 3.6.1)

Code to reproduce:

```

public class A
{
  public long Id {get;set;}
  public string Text {get;set;}
}

...

using (var session = stroe.LightweightSession()) 
{
var a = new A {Id = 2089063581810168873, Test="foo"};
session.Insert(a);
session.SaveChanges();

session.Patch(_=>_.Id == 2089063581810168873).Set(_=>_.Text, "bar");
session.SaveChanges();

var aNew = _session.Query<A>().First();
// aNew.Id is now 2089063581810168800 , the Id in the DB Field however is still correct
}
...

```

![grafik](https://user-images.githubusercontent.com/1822735/61270703-baadbe80-a7a2-11e9-8dba-9a1df392e972.png)

**Comment by mysticmind** [comment] 2019-07-16 07:26
@kinl99 Patch uses PLV8 so it is possibly something to do with PLV8/Javascript handling of long values in JSON. We will take a look at it and confirm.

**Comment by mysticmind** [comment] 2019-07-17 09:59
If I run a test using this SQL statement `select public.mt_transform_patch_doc('{"Id": 2089063581810168873, "Text": "bar"}', '{"type":"set","value":"bar","path":"Text"}')`, it returns `{"Id": 2089063581810168800, "Text": "bar"}`. In summary, `mt_patching.js` script looks to be messing up with the long value.

@kinl99 As an idiomatic usage, you shouldn't be updating the `Id` value in the JSON since it is the same value as the primary key value in `id` column. That said, this issue is applicable for any other long property/field in the JSON.

**Comment by oskardudycz** [comment] 2019-07-17 10:55
Yes, in general Javascript doesn't support long properly. It needs to be handled as text to allow proper values. If JavaScript get the value that's bigger than max value then it just truncates what's over. Maybe some serializer options would solve it, or extension to our custom contract resolver. 

Although that will be breaking change, as the serialized type will change.

**Comment by cocowalla** [comment] 2019-07-17 13:09
Not sure if this helps right now, but v8 now supports BigInt, and Plv8 3.x has [added support(https://github.com/plv8/plv8/issues/304#issuecomment-488710950) for BigInt (though there may still be serialisation issues)

**Comment by kinl99** [comment] 2019-07-17 15:44
@cocowalla a build of a new docker image with 11.4 and v8 2.3.13 is currently running. I'll retest once it's ready.

**Comment by cocowalla** [comment] 2019-07-17 16:41
@kinl99 you're going to need a build of Plv8 3.0 alpha too, which is unlikely to be fun to build :smile:

As an aside, is your Dockerfile public? I'd be interested in a Docker image with Postgres 11.4 and plv8 2 3.12/2.3.13 :smile:

**Comment by oskardudycz** [comment] 2019-07-17 16:43
Just too give you heads up - I’m also not sure if Npgsql supports that properly, that might be another case that’s needed to be confirmed 😉

**Comment by cocowalla** [comment] 2019-07-17 16:52
@oskardudycz I'm using a 64-bit integer property in one of my Marten document types, and it works (although I recall it was a bit fiddly for some reason - I'll try to remember to check on that and report back). I don't use the patch API with it though.

**Comment by oskardudycz** [comment] 2019-07-17 16:53
@cocowalla thank you for the feedback 👍

**Comment by smaktacular** [comment] 2019-07-17 17:12
> @kinl99 you're going to need a build of Plv8 3.0 alpha too, which is unlikely to be fun to build smile

right, should've read your post more carefully :)

> As an aside, is your Dockerfile public? I'd be interested in a Docker image with Postgres 11.4 and plv8 2 3.12/2.3.13 smile

sure, plesase see: [https://github.com/clkao/docker-postgres-plv8/pull/35/commits/6d121f25cc02c5bd89c3e86e7df42e0e6c6c297c] 

just change 11.2 to 11.4 in the from directive

**Comment by mronnblom-cint** [comment] 2020-02-05 17:01
Is there any update on this? 

I can confirm that this is still a problem with Postgres 11.5, PLV8 2.3.13 and Marten 3.10.0.

**Comment by mysticmind** [comment] 2020-02-05 18:20
You will need to try with plv8 3.x which is still alpha and not yet
released. Please note that this is not a Marten issue which requires a fix.

**Comment by mronnblom-cint** [comment] 2020-02-06 09:36
> You will need to try with plv8 3.x which is still alpha and not yet released. Please note that this is not a Marten issue which requires a fix.

Well, since Marten relies rather heavily on PLV8, this _becomes_ a Marten issue IMHO, since we can't use long with patching/transforms. But I do understand that there's nothing to do about it in the Marten codebase. It would be good to include this in the docs though, since not everyone will find this post (before it's too late).

**Comment by mysticmind** [comment] 2020-02-06 09:50
It is a good idea to add docs on this subject to provide clarity, we will
add it. Thank you!

**Comment by jeremydmiller** [comment] 2020-09-17 20:56
I played with this a little bit today, and I can definitely reproduce the issue with a very recent plv8. I think I'm voting to table this until we get back to v4 patching work. I **think** we play the story that tries to use native postgres operators wherever possible in the patching to possibly sidestep this (and as a performance optimization anyway)

**Comment by mysticmind** [comment] 2020-09-18 01:23
@jeremydmiller what version of plv8 did you try with?

**Comment by cocowalla** [comment] 2020-09-18 07:31
Also interested to know, because if it was 3.x I'd love to know the build steps so I can create a Docker image! (plv8 has never been a "just works" kind of thing to build!)

**Comment by oskardudycz** [comment] 2020-09-18 07:36
@jeremydmiller plus one from me. To me, it's surprising that there is a version that this is working fine. As I wrote above (https://github.com/JasperFx/marten/issues/1315#issuecomment-512205446) - javascript is not able to handle .NET long, as the JS number has a much smaller range. So unless there is a custom mapping to/from string then, in my opinion, it won't work.

**Comment by mysticmind** [comment] 2022-03-04 15:27
Added a warning in docs via https://github.com/JasperFx/marten/commit/32e9c849e937005d7d845b203a6de4c25c64a1c0 to use PLV8 3.x when using long/big int for document id or any other properties while doing patch operation.

Refer to #1834 for an aggregated list of patch related issues. Closing this one.

**Closed by mysticmind** 2022-03-04 15:27 UTC
Labels: bug, patch, plv8
