### ISSUE TITLE
Concurrency problem Marten_v4.0.2

### ISSUE THREAD

**Issue by xevilmaxx** [JasperFx/marten#1953] opened 2021-10-28 10:24 UTC
Hi,
Thanks in advance for work you do.
I wanted to try migrate to **Marten4.0.2** from latest Marten3.13.4

---

**Use case:**
x4 Microservices which communicate between them through GRPC.
Each microservice on startup and during lifetime makes access to DB (each on their own).
OS: Debian10 (Raspberry Pi 3)

---

**Trouble:**
When using Marten4 if i run single microservice at time all seems apparently ok.
But if i run them together, OS almost stucks (mouse pointer can still move but very very slow and jumply) and only thing i can do is to reboot.

After reboot i can see that connection to DB were successfull, but when each service tries to fetch data from config table / scheme all are stuck there.

---

**Solution:**
Rollback to Marten3, where after fresh compiling it still works fine.

---

**Sample of function where probably all stucks:**
Becouse last log visible is:
_GetConfigs Invoked! DevceId: ..._

```
public JsonDeviceConfigs GetConfigs(long DeviceId)
        {
            try
            {

                log.Debug($"GetConfigs Invoked! DevceId: {DeviceId}");

                JsonDeviceConfigs result = null;

                using (var session = DbFactory.GetContext().QuerySession())
                {
                    //just for debugging
                    //var tmp = session.Query<JsonDeviceConfigs>().ToList();

                    //get somthing, if nothing return new of the config object
                    result = session.Query<JsonDeviceConfigs>()
                        .Where(x => x.Id == DeviceId)
                        .FirstOrDefault()
                        ??
                        new JsonDeviceConfigs();
                }

                return result;

            }
            catch (Exception ex)
            {
                log.Error(ex);
                return new JsonDeviceConfigs();
            }
        }
```

---

**And here is my DbFactory:**

```
public static class DbFactory
    {

        private static readonly NLog.Logger log = NLog.LogManager.GetCurrentClassLogger();

        public static DocumentStore Context { get; private set; } = null;

        /// <summary>
        /// Locks thread execution until DB is ready to accept us
        /// </summary>
        public static void EnsureDbStarted()
        {
            try
            {
                log.Debug("EnsureDbStarted Invoked!");

                DocumentStore res = null;
                do
                {
                    res = GetContext();
                    if(res == null)
                    {
                        log.Debug("Will wait a bit before attempting next connection!");
                        Thread.Sleep(5000);
                    }
                } 
                while (res == null);


                log.Debug("EnsureDbStarted DONE!");
            }
            catch(Exception ex)
            {
                log.Error(ex);
            }
        }

        public static DocumentStore GetContext()
        {
            try
            {

                if(Context == null)
                {

                    //var cfg = GetConfigs();
                    var connectionString = GetConnectionString();

                    log.Debug($"Connection String: {connectionString}");

                    Context = DocumentStore.For(_ => 
                    {

                        //Custom connection string
                        _.Connection(connectionString);

                        _.NameDataLength = 250;

                        //Custom Schema Name
                        _.DatabaseSchemaName = "ParkO_RTS";

                        //add json indexes also
                        // Add a gin index to Company's json data storage
                        //may be commented if performance is poor and you dont need do much readings
                        _.Schema.For<Transit>().GinIndexJsonData();
                        _.Schema.For<User>().GinIndexJsonData();
                        _.Schema.For<JsonDeviceConfigs>().GinIndexJsonData();
                        _.Schema.For<DynamicKey>().GinIndexJsonData();
                        _.Schema.For<Event>().GinIndexJsonData();
                        _.Schema.For<LanguageResource>().GinIndexJsonData();
                        _.Schema.For<SerialNumber>().GinIndexJsonData();

                        //My custom override for comparing objects not supported by Marten natively (for now alpha-8)
                        //Doable only in Marten >= v4
                        //_.Linq.MethodCallParsers.Add(new LinqEqualsExt());

                    });

                }
                return Context;

            }
            catch(Exception ex)
            {
                log.Error(ex);
                return null;
            }
        }

        private static string GetConnectionString()
        {
            try
            {
                log.Debug("GetConfigs Invoked!");

                string connStr = "host=127.0.0.1;database=postgres;password=pwd;username=postgres;";
                string jsonSettingsFile = "AppSettings.json";

                if (File.Exists(jsonSettingsFile) == true)
                {

                    log.Debug("JSON Config File Found!");

                    JObject data = JObject.Parse(File.ReadAllText(jsonSettingsFile, Encoding.UTF8));

                    connStr = data["ConnectionStrings"]["Postgres"].ToString();

                }
                else if (ConfigurationManager.ConnectionStrings["Postgres"] != null)
                {

                    log.Debug("Will try to search in App.config");
                    
                    connStr = ConfigurationManager.ConnectionStrings["Postgres"].ConnectionString;

                }
                else
                {
                    log.Debug($"Will leave to default value: {connStr}");
                }

                return connStr;

            }
            catch (Exception ex)
            {
                log.Error(ex);
                return null;
            }
            
        }

    }
```

**Comment by oskardudycz** [comment] 2021-11-15 08:22
@xevilmaxx, closing the issue. If you're still facing the issue, please send more feedback, then I can reopen it 👍

**Comment by xevilmaxx** [comment] 2021-11-16 08:11
Hi,
I just did a little test again with v4.1.0 (still same issue)
I still didn't looked on how to pre-build generated types (becouse adopted Marten to avoid additional DB headakes), maybe will in the future.

Regarding lock, unfortunately i think it wont solve my problem.
Becouse even if Context is static var, it's not shared across AppDomains in C#
_As stated also here:
https://stackoverflow.com/questions/42340520/are-static-class-shared-between-appdomain_

So i started locally service1 and verified that Context got populated.
Than i started Service2 with Service1 still running (that uses exactly same class) and Context were again null and needed to be recreated.
So static variables are not visible to another instances of services, therefore also lock won't help.
While inside each microservice it's impossible that there will be multiple accesses at same time (at least for now).

More that that the logic is that services can start in whatever order they want,
specifically problem occurs when starting multiple services almost simultaneously (becouse they are started by script or systemctl).
In that moment Context is getting created in multiple instances (becouse each one is unaware of another) and system get stuck, 3 microservices are enough to collapse RaspberryPi3B+.
While Marten v3.x can handle such situation without particular problems, even with 5 or more microservices.

**Comment by oskardudycz** [comment] 2021-11-16 08:25
@xevilmaxx, pre-build generated types are dedicated specifically for the case that you described. It cuts the initialisation time to not do code generation while initialising context. Could you try to do that and confirm if the issue is still happening?

@jeremydmiller FYI.

**Comment by xevilmaxx** [comment] 2021-11-16 10:06
Ok, i gave it a quick shot.

Followed this guide:
https://martendb.io/configuration/prebuilding.html#pre-building-generated-types

Tried to install required NuGet package:
and run following commands (multiple times):
dotnet run -- codegen preview
dotnet run -- codegen write

commands were executed and Console runned as expected but by telling also:
Unable to find a pre-built storage type for IEventStorage
Unable to use pre-built type for LibRtDb.DTO.DynamicKeys.DynamicKey
Unable to use pre-built type for LibRtDb.DTO.DeviceConfigs.JsonDeviceConfigs
Unable to use pre-built type for GenericAPIProtos.User
Unable to use pre-built type for GenericAPIProtos.Transit
Unable to use pre-built type for LibRtDb.DTO.SerialNumbers.SerialNumber
Unable to use pre-built type for LibRtDb.DTO.Languages.LanguageResource
Unable to use pre-built type for LibRtDb.DTO.Events.Event


From PackageManagerConsole and from Git BASH in folder of destination of runnable project.
Project runned, but i didnt found any generated folder  in project or in ./bin/Debuf/net5.0/Internal/Generated/

So briefly i wasn't able to generate pre-compiled files.

**Comment by oskardudycz** [comment] 2021-11-16 10:28
@xevilmaxx, thanks for the heads-up, are those types public? Could you provide us with a sample project?

**Comment by jeremydmiller** [comment] 2021-11-16 11:32
@xevilmaxx The generated code is written to the project itself where the code would be generated into the main applicaiton assembly itself, not deep in the /bin/blah/blah folders.

If you're getting this:

"Unable to use pre-built type for LibRtDb.DTO.DynamicKeys.DynamicKey" -- that just means that there is no code pre-generated within the assembly for that type. You would see the types under /Internal/Generated. You do have to "tell" Marten about the document types upfront.

A couple other things:

* I'd argue that using IHostBuilder and then relying on `Add/UseMarten()` to do the bootstrapping would actually simplify your code over the manual singleton thing you've got going on
* This is gonna sound weird, but put a random Thread.Sleep or Task.Delay() in your startups so that every service doesn't try to compile all at the same time when the microservices are all started up

**Comment by jeremydmiller** [comment] 2021-11-16 13:15
@oskardudycz @xevilmaxx I've finally woken up a bit, so **Duh, Jeremy**, the codegen command is using the registrations in the `IHostBuilder` for the application, in this case including the Marten registrations. For that command to work, you need to be bootstrapping Marten through a `HostBuilder` with the `Add/UseMarten()` extension methods.

**Comment by xevilmaxx** [comment] 2021-11-17 11:34
Hi, i made a simple prototype of how i trying to use Marten (by making minimal changes to DB library).
https://github.com/xevilmaxx/MartenColdStart
Each micro-service can have AppSetting.json file in which you can specify connection string to db.
You just need to set CopyIfNewer in file properties for AppSettings.json.

Was trying to Generate Pre-Compiled in MicroService0/Program.cs but for now without much success.
I get:
```

Searching 'LamarCodeGeneration.Commands, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' for commands
ERROR: System.InvalidOperationException: No service for type 'LamarCodeGeneration.DynamicCodeBuilder' has been registere
d.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider
provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequired
Service[T](IServiceProvider provider)
   at LamarCodeGeneration.Commands.GenerateCodeCommand.Execute(GenerateCodeInput
input)
   at Oakton.OaktonCommand`1.Oakton.IOaktonCommand.Execute(Object input)
   at Oakton.CommandRun.Execute()

at Oakton.CommandExecutor.execute(CommandRun run)
```

On my PC even if i run 5 services together all seems ok in this particular scenario.
Eventually will do more investigation on Raspberry asap.

**Comment by xevilmaxx** [comment] 2021-11-17 11:48
Ok, indeed by following current guide by letter generation was successfull.
Is there any way i can handle those special commands to generate pre-build types on my own (maybe with some king of post-build script)?
Or at least can you suggest me where to look in marten source code?
Thanks.

**Comment by xevilmaxx** [comment] 2021-11-19 14:19
Hi,

----

Regarding locking:

**I finally found the solution to create a system wide locks in C# (not only inside 1 micro-service but across all)**

```csharp
//Really important to put: Global\\ before mutex name, in order to ensure it's system wide
public static Mutex MartenDb = new Mutex(false, "Global\\MartenMutex");

//Acquire lock
MartenDb.WaitOne();

//Release lock
MartenDb.ReleaseMutex();
```

**So here is full example:**

```csharp

public static Mutex MartenDb = new Mutex(false, "Global\\MartenMutex");

....

public static DocumentStore GetContext()
{
    bool isLockAcquired = false;
    try
    {
        if(Context == null)
        {

            MartenDb.WaitOne();
            isLockAcquired = true;
            log.Trace("Lock Acquired!");

            var connectionString = GetConnectionString();

            log.Debug($"Connection String: {connectionString}");

            Context = DocumentStore.For(_ => 
            {
                // (...)
            });

            if(isLockAcquired == true)
            {
                //Release GLOBAL mutex, so eventually others can continue
                MartenDb.ReleaseMutex();
                isLockAcquired = false;
                log.Trace("Lock Released!");
            }

        }
        return Context;

    }
    catch(Exception ex)
    {
        log.Error(ex);

        if(isLockAcquired == true)
        {
                //Release GLOBAL mutex, so eventually others can continue
                MartenDb.ReleaseMutex();
                isLockAcquired = false;
                log.Trace("Lock Released!");
        }

        return null;
    }
}
```

----

After some deploys, with Marten3 i was able to read logs and ensure that locking mechanism is working good also on Linux.
So i tried to upgrade to Marten4 (v4.1.0) again.

Firstly i executed code with sample above, and even if lock has worked, Raspberry stucked on first attempt of data fetching.
Then i added lock also in that function which fetches data, but it's stuck anyway (almost all services call it during initialization with some id).
I also added table CSV from which i'm trying to fetch.

```csharp
public JsonDeviceConfigs GetConfigs(long DeviceId)
        {
            try
            {

                GlobalMutexLocks.MartenDb.WaitOne();

                log.Debug($"GetConfigs Invoked! DevceId: {DeviceId}");

                JsonDeviceConfigs result = null;

                using (var session = DbFactory.GetContext().QuerySession())
                {
                    //just for debugging
                    //var tmp = session.Query<JsonDeviceConfigs>().ToList();

                    //get somthing, if nothing return new of the config object
                    result = session.Query<JsonDeviceConfigs>()
                        .Where(x => x.Id == DeviceId)
                        .FirstOrDefault()
                        ??
                        new JsonDeviceConfigs();
                }

                GlobalMutexLocks.MartenDb.ReleaseMutex();

                return result;

            }
            catch (Exception ex)
            {
                log.Error(ex);
                GlobalMutexLocks.MartenDb.ReleaseMutex();
                return new JsonDeviceConfigs();
            }
        }
```


Marten4 failure logs, based on my system:
https://we.tl/t-1ut5sHnoOv

There is something strange in Marten4...

**Comment by xevilmaxx** [comment] 2021-11-19 14:59
Just noticed, when i went back to Marten3, now i got this message:

```
2021-11-19 15:48:43.5267 DEBUG LibRtDb.Services.ConfigsService - GetConfigs Invoked! DevceId: 1
2021-11-19 15:48:48.5284 DEBUG LibRtDb.DTO.RuntimeConfigs.GenericRuntimeConfigs - Its first boot, lets also check existance for all needed vars
2021-11-19 15:48:48.8019 DEBUG LibRtDb.Services.ConfigsService - SetConfigs Invoked!
2021-11-19 15:48:49.6783 ERROR LibRtDb.Services.ConfigsService - Marten.Exceptions.MartenCommandException: Marten Command Failure:$
select parko_rts.mt_upsert_jsondeviceconfigs(doc := :arg0, docDotNetType := :arg1, docId := :arg2, docVersion := :arg3)$
$
42704: constraint "pk_mt_doc_jsondeviceconfigs" for table "mt_doc_jsondeviceconfigs" does not exist
 ---> Npgsql.PostgresException (0x80004005): 42704: constraint "pk_mt_doc_jsondeviceconfigs" for table "mt_doc_jsondeviceconfigs" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Marten.Services.UpdateBatch.<>c__DisplayClass25_1.<Execute>b__0(NpgsqlCommand c)
   at Marten.Services.ManagedConnection.<>c__DisplayClass35_0.<Execute>b__1()
   at Marten.NulloRetryPolicy.Execute(Action operation)
   at Marten.Services.ManagedConnection.Execute(NpgsqlCommand cmd, Action`1 action)
  Exception data:
    Severity: ERROR
    SqlState: 42704
    MessageText: constraint "pk_mt_doc_jsondeviceconfigs" for table "mt_doc_jsondeviceconfigs" does not exist
    Where: SQL statement "INSERT INTO parko_rts.mt_doc_jsondeviceconfigs ("data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pk_mt_doc_jsondeviceconfigs
  DO UPDATE SET "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp()"
PL/pgSQL function parko_rts.mt_upsert_jsondeviceconfigs(jsonb,character varying,bigint,uuid) line 5 at SQL statement
    File: pg_constraint.c
    Line: 965
    Routine: get_relation_constraint_attnos
   --- End of inner exception stack trace ---
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Services.ManagedConnection.Execute(NpgsqlCommand cmd, Action`1 action)
   at Marten.Services.UpdateBatch.Execute()
   at Marten.Services.UnitOfWork.ApplyChanges(UpdateBatch batch)
   at Marten.DocumentSession.SaveChanges()
   at LibRtDb.Services.ConfigsService.SetConfigs(List`1 Configs) in C:\Users\maxym.oboyshev\source\repos\ParkO_V3\ADVANCED_RTS\RT_DB\LibRtDb\Services\ConfigsService.cs:line 342
Marten.Exceptions.MartenCommandException: Marten Command Failure:$
select parko_rts.mt_upsert_jsondeviceconfigs(doc := :arg0, docDotNetType := :arg1, docId := :arg2, docVersion := :arg3)$
$
42704: constraint "pk_mt_doc_jsondeviceconfigs" for table "mt_doc_jsondeviceconfigs" does not exist
 ---> Npgsql.PostgresException (0x80004005): 42704: constraint "pk_mt_doc_jsondeviceconfigs" for table "mt_doc_jsondeviceconfigs" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Marten.Services.UpdateBatch.<>c__DisplayClass25_1.<Execute>b__0(NpgsqlCommand c)
   at Marten.Services.ManagedConnection.<>c__DisplayClass35_0.<Execute>b__1()
   at Marten.NulloRetryPolicy.Execute(Action operation)
   at Marten.Services.ManagedConnection.Execute(NpgsqlCommand cmd, Action`1 action)
  Exception data:
    Severity: ERROR
    SqlState: 42704
    MessageText: constraint "pk_mt_doc_jsondeviceconfigs" for table "mt_doc_jsondeviceconfigs" does not exist
    Where: SQL statement "INSERT INTO parko_rts.mt_doc_jsondeviceconfigs ("data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pk_mt_doc_jsondeviceconfigs
  DO UPDATE SET "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp()"
PL/pgSQL function parko_rts.mt_upsert_jsondeviceconfigs(jsonb,character varying,bigint,uuid) line 5 at SQL statement
    File: pg_constraint.c
    Line: 965
    Routine: get_relation_constraint_attnos
   --- End of inner exception stack trace ---
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Services.ManagedConnection.Execute(NpgsqlCommand cmd, Action`1 action)
   at Marten.Services.UpdateBatch.Execute()
   at Marten.Services.UnitOfWork.ApplyChanges(UpdateBatch batch)
   at Marten.DocumentSession.SaveChanges()
   at LibRtDb.Services.ConfigsService.SetConfigs(List`1 Configs) in C:\Users\maxym.oboyshev\source\repos\ParkO_V3\ADVANCED_RTS\RT_DB\LibRtDb\Services\ConfigsService.cs:line 342    at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Services.ManagedConnection.Execute(NpgsqlCommand cmd, Action`1 action)
   at Marten.Services.UpdateBatch.Execute()
   at Marten.Services.UnitOfWork.ApplyChanges(UpdateBatch batch)
   at Marten.DocumentSession.SaveChanges()
   at LibRtDb.Services.ConfigsService.SetConfigs(List`1 Configs) in C:\Users\maxym.oboyshev\source\repos\ParkO_V3\ADVANCED_RTS\RT_DB\LibRtDb\Services\ConfigsService.cs:line 342
2021-11-19 15:48:50.4928 DEBUG LibRtDb.Services.DyncamicKeysService - No new dynamic keys to add
2021-11-19 15:48:50.5563 TRACE LibRtDb.Extensions.JsonDeviceConfigsExt - [listening_port : 50051] will simply change type to: System.Int32
2021-11-19 15:48:51.3776 DEBUG LibRtDb.Extensions.JsonDeviceConfigsExt - listening_port -> 50051
2021-11-19 15:48:51.4582 TRACE LibRtDb.Extensions.JsonDeviceConfigsExt - [passage_mode : 1] will simply change type to: System.Int32
2021-11-19 15:48:51.4582 DEBUG LibRtDb.Extensions.JsonDeviceConfigsExt - passage_mode -> 1
2021-11-19 15:48:51.4582 DEBUG LibCore.CoreManager - Working mode: Simple
```

So i suppose probably there might be something strange in Migration meccanisms from Marten3 -> Marten4 that is particularly slow?
Will also try to do a clean db generation with Marten4.

**Comment by jeremydmiller** [comment] 2021-11-22 15:52
@xevilmaxx Go to the very, very latest version of Marten 4 to have it correctly deal with the primary key naming problems going from Marten 3 to Marten 4.

**Comment by xevilmaxx** [comment] 2021-11-22 16:00
Ok, probably i found possible issue, (at least on linux)
**Executed run with only 2 microservice enabled in both cases.**

Here is RAM consumption with Marten3
![image](https://user-images.githubusercontent.com/17651554/142892803-264db178-3622-4d80-8310-9543c0463a01.png)

And here is with Marten4 (which eats a lot more):
In the end, it finishes by killing the machine.
**Dont mind about quantity of repeated entries (i just made a photo in thread mode not executable mode)**
![IMG_20211122_154434](https://user-images.githubusercontent.com/17651554/142893562-540c79c5-63c7-4dae-9152-9d015e7b41f1.jpg)

**Comment by jeremydmiller** [comment] 2021-11-22 18:10
@xevilmaxx So what is it we're supposed to see here? Can you do a memory dump and show where the memory is being held? This isn't actionable in any way.

**Comment by xevilmaxx** [comment] 2021-12-15 09:07
Hi,
Since Marten4 is not convincing me, for now i found a way to have a backup option in emergency case.
I made a wrapper around Marten3 and LiteDb, so i can switch between them easily just by changing DbType in configs.

It supports basic CRUD operations and most basic Linq Query features (all i need for now).
Made a dedicated rudimental Async Engine (1 dedicated thread only at most) in order to support async calls.
As also saw that Marten doesnt allow to do a query with linq in async way, at least Marten3.

API is much similar to Marten one.

**Here is the repo:**
https://github.com/xevilmaxx/NoSqlGenericWrapper

**Comment by oskardudycz** [comment] 2021-12-15 10:06
@xevilmaxx, well, it does allow to query with LINQ with `ToListAsync`, what feature are you missing? Regarding Marten 4, it'd be good if you provided us with more information on your issues. Did you try the latest Marten version using Pre Built types? Recently we added fixes related to Blazor usage and got positive feedback that it's working fine.

**Comment by jeremydmiller** [comment] 2021-12-15 12:01
@xevilmaxx Honestly, I don't think we're going to be able to help you with this without a lot more information. We aren't getting reports like this from anyone else, and your Marten setup is non-idiomatic. We do have some ideas in the book to make the pre-built types easier to use in a future version for folks who aren't using `AddMarten()` bootstrapping, but I think that won't show up until next year. 

And Marten has supported async LINQ query operators since < 1.0, so I'm not sure what you're talking about.

**Comment by jeremydmiller** [comment] 2022-02-14 11:45
No recent activity, and I don't think there was anything actionable here anyway.

**Closed by jeremydmiller** 2022-02-14 11:45 UTC
Labels: question, wontfix
