### ISSUE TITLE
4.0.0-alpha.4 - LamarCompiler erroring to console regarding "Could not make an assembly reference to mscorlib" when running in .NET 5 

### ISSUE THREAD

**Issue by kieranbenton** [JasperFx/marten#1688] opened 2020-12-31 13:53 UTC
I've not managed to narrow down exactly where this is being dumped to the console exactly. It otherwise doesn't seem to be affecting the operation of Marten.

'zxing' (https://www.nuget.org/packages/ZXing.Net/) seems to be involved in this? It hasn't been updated in some time so wonder if LamarCompiler is making some new assumptions about it in a .NET 5 context?

Just let me know if you need me to try anything/more information.

```
Could not make an assembly reference to mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Threading.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at LamarCompiler.AssemblyGenerator.ReferenceAssembly(Assembly assembly)

```

```
Could not make an assembly reference to zxing, Version=0.16.6.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60

System.IO.FileNotFoundException: Could not load file or assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at LamarCompiler.AssemblyGenerator.ReferenceAssembly(Assembly assembly)
```

**Comment by kieranbenton** [comment] 2020-12-31 13:53
Might be related to: https://github.com/JasperFx/marten/issues/1619 ?

**Comment by jeremydmiller** [comment] 2020-12-31 21:05
@kieranbenton Hey man, this is gonna suck, but it's something in your dependency stack of the app I'd guess. LamarCompiler is greedy -- and has to be -- about referenced assemblies. It generally needs to do a recursive walk up the assembly dependencies to make things compile, but has a try/catch "write to the console instead" block that swallows resolution problems exactly like you're seeing here. 

Something in your system has a reference to that particular version of PresentationCore and it's not present. If it's working though, then Marten is gonna function normally and you'll only see this on the initial code compilation for each document type and/or the event store

**Comment by kieranbenton** [comment] 2021-01-01 11:41
No problem @jeremydmiller - least I know and can go spelunking elsewhere! I reckon it might be zxing - its pretty old (stable) now.

Good to confirm its not necessarily something to worry about. 

Can you point me towards the code in LamarCompiler that does this so I can learn about it? It might help me figure out where the problem is, especially given I'm not actually sure what LamarCompiler's role is - I assume its to do with serialization in marten but I don't understand why it would need to walk the full dependency tree yet.

Happy new year!

**Comment by jeremydmiller** [comment] 2021-02-10 18:06
This is annoying, but it's not a bug and doesn't impact Marten functionality. I'm closing this as it isn't actionable

**Closed** 2021-02-10 18:06 UTC
