### ISSUE TITLE
child object filtering / sorting does not work

### ISSUE THREAD

**Issue by timdoke** [JasperFx/marten#1200] opened 2019-02-21 21:24 UTC
Please see the attached POC of the issue.  I discussed briefly on gitter chat about this issue with @oskardudycz .  It will work fine as long as you don't have to do any type of querying on the child object.

[MartenSubObjectTest.zip](https://github.com/JasperFx/marten/files/2891319/MartenSubObjectTest.zip)

**Comment by mysticmind** [comment] 2019-04-25 17:37
Looks like a duplicate of #870, closing this one.

**Closed by mysticmind** 2019-04-25 17:37 UTC
Labels: bug, linq
