### ISSUE TITLE
ArgumentException occurs using StorageOperationWithDeletionsComparer

### ISSUE THREAD

**Issue by malclear** [JasperFx/marten#1431] opened 2020-02-25 19:05 UTC
When there is a session having deletions to two or more document types, where those documents have the same types of primary keys (and duplicates at that), then when calling SaveChangesAsync, I get the following message: 
```
---> System.ArgumentException: Unable to sort because the IComparer.Compare() method returns 
inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared 
to another value yields different results. IComparer: 
'Marten.Services.UnitOfWork+StorageOperationWithDeletionsComparer'.
at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
 at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
at Marten.Services.UnitOfWork.determineChanges(UpdateBatch batch)
at Marten.Services.UnitOfWork.buildChangeSet(UpdateBatch batch)
at Marten.Services.UnitOfWork.ApplyChangesAsync(UpdateBatch batch, CancellationToken token)
         at Marten.DocumentSession.SaveChangesAsync(CancellationToken token)
         at blah, blah, blah (my stuff here)
```
So, for example, there is a deletion each for the types Document_A and Document_B. If they both use the same identifier for the document record, then I get the message shown above.

If I adjust the identifiers by appending a magic string specific to the document type, the problem does not occur.
Hopefully, I'm just missing something in the docs.

**Comment by oskardudycz** [comment] 2020-05-19 17:59
@malclear I apologize for the late answer. I added PR with tests trying to reproduce your case, however, it seems that they're passing and I cannot reproduce the described issue. 

@malclear could you verify if I'm doing the same case like yours?

Could you also provide your document store config and your document structure? Do you have some overloads of the GetHashCode or Equals?

**Comment by jeremydmiller** [comment] 2020-05-22 20:14
Looking at the code, I'm not seeing how that would happen, but I'd also guess we need more operations of some sort in there to bring it out.

**Comment by oskardudycz** [comment] 2020-06-03 18:22
@malclear I'm closing for now with #1478. If you're still having the issue please provide additional reproduce steps or send PR with the updated fail scenario that I added in #1478.

**Closed by oskardudycz** 2020-06-03 18:22 UTC
Labels: bug
