### ISSUE TITLE
Marten.CommandLine - projections ShardTimeout ignores input

### ISSUE THREAD

**Issue by iamjustsam** [JasperFx/marten#2418] opened 2022-12-06 13:41 UTC
Any shard timeout you pass to the `projections` command, seems to be ignored. I did some digging and I think this is caused by the fact that the TimeSpanConverter in JasperFx/baseline is not registered (See: https://github.com/JasperFx/baseline/blob/master/src/Baseline/Conversion/Conversions.cs)

Changing the type of the ShardTimeout argument to string and doing the conversion explicitly in the `ProjectionController` seems to do the trick:
![image](https://user-images.githubusercontent.com/772178/205927824-5d692a07-435a-42b1-bb66-c428eb6466c5.png)

**Comment by mysticmind** [comment] 2022-12-10 17:35
Duplicate of https://github.com/JasperFx/marten/issues/2400

**Comment by mysticmind** [comment] 2022-12-10 17:36
@iamjustsam Thanks for the input, I will be looking to fix this by start of next week.

**Comment by mysticmind** [comment] 2022-12-12 08:20
GH-2400 is fixed. Closing this as duplicate.

**Closed by mysticmind** 2022-12-12 08:20 UTC
