### ISSUE TITLE
Doing a negation when using LINQ's ".Any()" in a child collection throws a not supported exception.

### ISSUE THREAD

**Issue by BusschaertTanguy** [JasperFx/marten#1413] opened 2020-01-22 22:02 UTC
When using the IQuerySession.Query<>(); on a projection, when doing a negation in the child collection of the elements, the following exception is thrown:

`   at Marten.Linq.CollectionAnyContainmentWhereFragment.gatherSearch(BinaryExpression x, Dictionary'2 search, ISerializer serializer)
   at Marten.Linq.CollectionAnyContainmentWhereFragment.gatherSearch(BinaryExpression x, Dictionary'2 search, ISerializer serializer)
   at Marten.Linq.CollectionAnyContainmentWhereFragment.<>c__DisplayClass8_0.<buildBinary>b__3(BinaryExpression x)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable'1 values, Action'1 eachAction)
   at Marten.Linq.CollectionAnyContainmentWhereFragment.<buildBinary>d__8.MoveNext()
   at System.Collections.Generic.List'1.InsertRange(Int32 index, IEnumerable'1 collection)
   at Marten.Linq.CollectionAnyContainmentWhereFragment.Apply(CommandBuilder builder)
   at Marten.Linq.Model.LinqQuery'1.AppendWhere(CommandBuilder sql)
   at Marten.Linq.Model.LinqQuery'1.ConfigureCommand(CommandBuilder sql, Int32 limit)
   at Marten.Linq.Model.LinqQuery'1.ConfigureCommand(CommandBuilder command)
   at Marten.Linq.QueryHandlers.ListQueryHandler'1.ConfigureCommand(CommandBuilder builder)
   at Marten.Util.CommandBuilder.ToCommand(ITenant tenant, IQueryHandler handler)
   at Marten.Services.CommandRunnerExtensions.Fetch[T](IManagedConnection runner, IQueryHandler'1 handler, IIdentityMap map, QueryStatistics stats, ITenant tenant)
   at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase'1.System.Collections.IEnumerable.GetEnumerator()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.<WriteResponseBodyAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.<WriteResponseBodyAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.<WriteResponseBodyAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeResultFilters>g__Awaited|27_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|19_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Awaited|17_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<<Invoke>g__AwaitRequestTask|6_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GameSociation.WebApi.Exceptions.ExceptionMiddleware.<Invoke>d__2.MoveNext() in D:\Projects\GameSociation.Backend\src\GameSociation.WebApi\Exceptions\ExceptionMiddleware.cs:line 22`,

here's the query in question.

`var foo = IQuerySession.Query<FooView>().Where(x => x.Bars.Any(y => y.A== "A" && y.B != "B"));`

I tested it by replacing the '!=' in the .Any by and '==' and it works fine, so the problem is the negation.

**Comment by Miggleness** [comment] 2020-01-27 23:42
`NotEqual` expression in `Any` isn't supported just yet due to its use of the contain operator (`@>`)

Marten converts expression in an `Any` to `d.data @> :{param.ParameterName}`

This is something which I believe will be addressed in #1201 

> Possibly use a Javascript library for JSONPath expressions in Postgresql for harder to reach queries? Especially within child collections.

**Comment by oskardudycz** [comment] 2020-01-28 09:05
@Miggleness I'm not sure if the Linq Overhaul won't be `4.1` as `4.0` will be mostly focused on Event Sourcing.

I'll try to look in the next few days if we can't squeeze it earlier.

p.s. thank you for the feedback and reproduce steps details 👍

**Comment by jeremydmiller** [comment] 2020-05-25 20:30
Yeah, this one's going to have to go in v4, but at least that starts soon.

**Closed** 2020-09-13 19:49 UTC
Labels: bug, linq
