### ISSUE TITLE
HiLoSequence Problem

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#505] opened 2016-08-31 19:26 UTC
We're seeing the following error message when there are concurrent requests to our web api that uses Marten (built using NancyFx):

`40001: could not serialize access due to concurrent update`

The `IsolationLevel` for the `HiLoSequence` is set to `Serializable` which seems to make sense, but I'm concerned with with less than 10 concurrent operations, we're seeing this error.

https://github.com/JasperFx/marten/blob/master/src/Marten/Schema/Identity/Sequences/HiLoSequence.cs#L61

Relevant Postgres docs:

https://www.postgresql.org/docs/9.5/static/transaction-iso.html

**Comment by jeffdoolittle** [comment] 2016-08-31 19:35
Perhaps time to introduce the ability to use postgres sequences for documents. Now that it's being used for the events, there's precedent for using sequences. Just sayin'.

**Comment by jeremydmiller** [comment] 2016-08-31 19:45
@jeffdoolittle That is a little nuts. Have you tried to move up the HiloSettings to fetch more at a time? I'd leave the isolation level alone and honestly opt for a retry.

As for the postgresql sequence, there's a reason why I didn't opt for that one off the bat; It'd require more code to be able to fetch id values on demand as part of IDocumentSession.Store()

**Comment by jeffdoolittle** [comment] 2016-08-31 19:51
Yeah, I saw this issue regarding sequences: https://github.com/JasperFx/marten/issues/66

My thought on that was "No Bulk Insert for You!" on documents that use sequences, rather than saying "don't use Marten if you want sequences." But whatev, I'm not opposed to HiLo just shocked that I'm having this issue with so few concurrent operations.

**Comment by jeffdoolittle** [comment] 2016-08-31 19:58
If I'm already experiencing this issue with the Marten default HiLo settings, then I'm thinking others are going to have problems with the HiLoSequence as well.

**Comment by jeremydmiller** [comment] 2016-09-01 12:45
@jeffdoolittle I can't reproduce this problem this morning. I'm absolutely hammering it using the hilo identity, but the worst I've been able to do is to cause timeout exceptions. For right now, I'm adding a single retry loop to the HiloSequence fetching. Can you check out your db and see if there's some kind of zombie connections or tx's on that hilo table maybe?

**Comment by jeffdoolittle** [comment] 2016-09-01 13:48
We'll take a deeper look later this morning (Our team is in California).

The issue occurred due to a misunderstanding of requirements. One of our devs was implementing a feature that needs to create multiple documents of the same type based on user settings (currently set to 9 at a time). He was making nine Api calls when it should have been a single api call with 9 created on the server side. But when the nine calls were made using Angular and executing with async promises, that's when this problem reared its ugly head.

Now that the 9 docs are created server side, the problem went away. But if 9 async operations is all it took to get this error, then we were concerned about resource contention with multiple users.

**Comment by jeremydmiller** [comment] 2016-10-03 19:44
@jeffdoolittle Is there any update on this one?

**Comment by jeffdoolittle** [comment] 2016-10-03 20:35
afaik we're good for now

**Comment by jeremydmiller** [comment] 2016-10-03 20:58
@jeffdoolittle I just read more closely over your message up above. I think I see the problem: "angular"

I'm closing this one then;)

**Closed by jeremydmiller** 2016-10-03 20:58 UTC

**Comment by jeffdoolittle** [comment] 2016-10-03 22:49
ha, probably unrelated, but touché :)
