### ISSUE TITLE
EventGraph.AliasesForEvents fails with NRE on a consecutive run of `MultiStreamProjection`-based projection

### ISSUE THREAD

**Issue by migajek** [JasperFx/marten#2650] opened 2023-07-18 12:54 UTC
When rebuilding projections, I'm getting a NRE in the following method:
![image](https://github.com/JasperFx/marten/assets/581492/1863f5b6-31fb-47af-b2ca-6e730f2ffe58)

There are indeed some null entries in the `_byEventName`:

![image](https://github.com/JasperFx/marten/assets/581492/7def0721-b54e-4f80-a44b-7a7b56577592)

1. it only happens for a `MultiStreamProjection`-based projections (I have only 3 of them, 15+ custom IProjections)
2. it happens only when some other projections were ran before. When running the `MultiStreamProjection`-based projection in question as a first one, `AliasesForEvents` is hit but the `_byEventName` cache is empty.
3. I am explicitly registering all known event types at startup. So far I have no idea where these `nulls` come from
4. Maybe, just maybe, there's something fishy about `Cache` behavior? I am not digging deeper at the moment but this doesn't feel right:
![image](https://github.com/JasperFx/marten/assets/581492/710e9706-72fa-4c91-b954-1fa91f5f1cc2)
![image](https://github.com/JasperFx/marten/assets/581492/069fd2dc-3533-4fe9-8310-eb7840268e41)

**Comment by Hawxy** [comment] 2023-07-18 12:59
This is resolved by #2647

**Comment by Hawxy** [comment] 2023-07-18 13:46
1. A custom `IProjection` isn't event clamped and will load all events from the database for processing.
2. During that load, a [lookup is made](https://github.com/JasperFx/marten/blob/999d371d2c84b397aa1e62cc544bfc55ebbc39fa/src/Marten/Events/EventDocumentStorage.cs#L235) based on the _name_ of the event to check if there's an existing mapping within the event graph (fast-path). If the value is missing, the name cache will do a [`FirstOrDefault` call to the type cache](https://github.com/JasperFx/marten/blob/999d371d2c84b397aa1e62cc544bfc55ebbc39fa/src/Marten/Events/EventGraph.cs#L54), therefore resulting in a null value being added if not found. If a null value gets returned, it uses the .net type name to perform an assembly lookup instead.
3. The `MultiStreamProjection` uses an event filter which checks for aliases for upcasting purposes, hitting the previously added null value.

When rebuilding a `MultiStreamProjection/SingleStreamProjection`, the type filter unintentionally prevents a null value being added to the name-based cache as it's already performed a type lookup, thus resulting in no values being missing when step 2 is performed above.

If you add a null-value breakpoint to the below line, you might be able to work out why a specific event is missing a mapping: https://github.com/JasperFx/marten/blob/999d371d2c84b397aa1e62cc544bfc55ebbc39fa/src/Marten/Events/EventDocumentStorage.cs#L235
Could be due to you just no longer using that event, I'm not sure.

The name cache being bypassed based on what projection type is rebuilt first is a bit off, maybe worth looking into @oskardudycz.

**Comment by migajek** [comment] 2023-07-18 14:50
@Hawxy thank you for this exhaustive explanation :) 
also thanks to your suggestion, I did `select distinct type, mt_dotnet_type from mt_events` only to find one of the event types has been carelessly moved to a different namespace couple of years ago. 
Thanks!

**Comment by migajek** [comment] 2023-07-18 15:18
and an update: the  only event type left that doesn't get mapped to my domain model assembly type is `Marten.Events.Operations.Tombstone, Marten` - also, there's one `null` left in the `_byEventName` .

**Comment by oskardudycz** [comment] 2023-07-19 08:08
@migajek, might be that we need to verify if we didn't miss the default mapping here.

**Comment by migajek** [comment] 2023-07-19 08:38
unfortunately I don't have time to investigate any longer at this point, I reordered the projections to be rebuild so that the `GeneratedProjections` are rebuilt first, then the unclamped custom projections and this seems to work for now.

The projection rebuilding is done by the standalone unit of deployment (migrator app), I haven't checked yet whether this issue occurs when running the projections inline (that is, in the usual app workflow). Will let you know. 

By the way, wouldn't it be beneficial to be able to explicitly ignore some events types? Either by "type" or "mt_dotnet_type"?
Over the years, several concepts of the application were dropped, therefore some events that are in the stream are not relevant anymore. There is no point in rewriting stream though, these events actually did happen and should we ever consider going back to any of the concepts, I'd like to have those past events there.
For now I've added all the event types in code (empty classes) but this doesn't feel clean.

**Comment by oskardudycz** [comment] 2023-07-19 10:04
As mentioned, in my opinion, calling AddEventType should not be required at all, as it’s tedious (although helpful for us). Regarding ignoring event types, that’s something to consider, although it should work fine already for stream aggregation. And should also work for projection when the fix for this issue is applied and released (so as it was before).

**Comment by migajek** [comment] 2023-07-19 11:44
Thanks. Will get back to this when I run projections again once this fix gets released

**Closed** 2023-07-20 12:57 UTC

**Comment by oskardudycz** [comment] 2023-07-20 13:38
@migajek, @Hawxy fix is merged, I'll try to do `6.0.5` release in the next few days. 

Yet, based on my research, if the type isn't found in the assembly or custom mapping defined, then event type resolution will fail. We need to tackle that as a dedicated issue, as it's currently by design, and it'll require careful additional work.
