### ISSUE TITLE
Marten deadlocks itself when called from a custom SynchronizationContext

### ISSUE THREAD

**Issue by bitbonk** [JasperFx/marten#2023] opened 2021-12-21 15:51 UTC
We do all of our Marten stuff in a worker service (derived from [BackgroundService](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-6.0)) that is started and run with a custom synchronization context (using [SingleThreadedSychronizationContext](https://github.com/bitbonk/MartenDeadlockRepro/blob/main/ReproApp/Threading/SingleThreadSynchronizationContext.cs)).

This worked fine in Marten `3.13.5` and `netcoreapp3.1` but after upgrading to Marten `4.3.0` and `net6.0`, Marten always deadlocks itself after it has successfully created its first `mt_doc_*` table.

This can be reproduced using https://github.com/bitbonk/MartenDeadlockRepro.
The call [Read\<Bar\>()](https://github.com/bitbonk/MartenDeadlockRepro/blob/d14a0357d5b56089edc4b5200003587360954f9b/ReproApp/ReproService.cs#L16) after a call of `Read<Foo>()` never completes.

Also note that two subsequent calls of the same type (e.g. calling `Read<Foo>()` twice) does not cause a deadlock. It is always the call with *a second* type that causes the deadlock.

My guess is that it has to do something with the session that gets asynchronously disposed with [await using var session = store.QuerySession();](https://github.com/bitbonk/MartenDeadlockRepro/blob/d14a0357d5b56089edc4b5200003587360954f9b/ReproApp/ReproService.cs#L28). Because if I inline the `Read<T>()` method like in the code below, I do not get any deadlocks.

```csharp
public override async Task StartAsync(CancellationToken cancellationToken)
{
    var store = DocumentStore.For("host=...");

    await using var session = store.QuerySession();
    var documents = await session
        .Query<Foo>()
        .ToListAsync(token: cancellationToken)
        .ConfigureAwait(true); //  true or false doesn't matter here, no deadlock

    await using var session1 = store.QuerySession();
    var documents1 = await session1
        .Query<Bar>()
        .ToListAsync(token: cancellationToken)
        .ConfigureAwait(false); //  true or false doesn't matter here, no deadlock

    await base.StartAsync(cancellationToken);
}
```

**Comment by jeremydmiller** [comment] 2021-12-21 20:58
@bitbonk It's the custom synchronization that's your culprit. In Marten <4, the automatic schema migration stuff is executed synchronously and inline, so there's no real issue. With Marten 4, *all* schema migrations has to run with async APIs because of our support for connection multi-plexing, so there's some .GetAwaiter().GetResult() action going on. I *think* that, or some kind of locking internal to Npgsql itself is your problem, because it's freezing up on a call to `NpgsqlCommand.ExecuteReaderAsync()`.

Good news is the easy workaround is to apply all Marten schema changes upfront and use `AutoCreate.None` for your `DocumentStore`. Harder workaround is to go fight with whatever that `SynchronizationContext` is in your codebase, or remove that. I confirmed that the code works as is once you remove the custom `SynchronizationContext`.

There's nothing actionable here in the Marten code IMO, so I'm actually going to close this.

**Closed by jeremydmiller** 2021-12-21 20:58 UTC

**Comment by bitbonk** [comment] 2021-12-22 08:23
@jeremydmiller This deadlock does not just happen with "our" `SynchronizationContext` I think it will happen in *any* synchronization context that does some sort of sequentialization. For example, the deadlock also happens in the classic WPF synchronization context as can be seen [here](https://github.com/bitbonk/MartenDeadlockRepro/blob/f1b0aabc9f880b4cc9d87b4e020e056d40c6abdd/ReproApp.Wpf/MainWindow.xaml.cs#L38).  I find that a bit worrysome.

**Comment by jeremydmiller** [comment] 2021-12-22 12:37
@bitbonk I gave you a workaround for Marten to get you past this, but otherwise, you're actually going to have to take it up with the Npgsql project itself. But for the moment, **you** have to prove first that it's not specific to your custom synchronization before you make that claim.

**Comment by bitbonk** [comment] 2021-12-22 12:45
As I said, I updated the repo project to prove the claim.

**Comment by jeremydmiller** [comment] 2021-12-22 12:46
Then you need to go to the Npgsql team, it's not a Marten issue. Or use the AutoCreate.None option I gave you above -- which would be a minor perf optimization anyway.
