### ISSUE TITLE
Index cannonicisation issue

### ISSUE THREAD

**Issue by bittercoder** [JasperFx/marten#3068] opened 2024-03-20 04:05 UTC
Just posting to say I have the same/similar issue to what's mentioned in this pull request and associated issues https://github.com/JasperFx/weasel/pull/120 https://github.com/JasperFx/marten/issues/2983, but it's not resolved by the fix for those that (which just targeted the `public` schema).

For my application I'm not using the default `public` schema, but a schema called `app` and here is what I'm observing.

*Environment:* AWS RDS Postgres with engine version 16.1.  I'm not able to reproduce this locally using a docker container, so it's something specific about that environment / postgres distribution from AWS I suspect.

Index generated by marten that was applied through Weasel.

```
CREATE INDEX mt_doc_document_idx_ngram_name ON app.mt_doc_document USING gin app.mt_grams_vector(COALESCE(data ->> 'Name', '')));
```

The Index DDL as reported by the database retrieved from psql using `pg_get_indexdef(i.oid)`

```
CREATE INDEX mt_doc_document_idx_ngram_name ON app.mt_doc_documen
t USING gin (mt_grams_vector((data ->> 'Name'::text)))
```

Notice the `app.` on the `app.mt_grams_vector` is missing.  If I tweak the DataConfig of the index to exclude the `app.` then I get errors when applying the migration.

Ideally I think when doing `CanonicizeDdl` on the index in Weasel, it needs to pass the parents schema into the method so it can be stripped out? Something like below. Though I'm unsure of what unintended side effects that might bring with it?

```
    /// <summary>
    ///     Method to normalize the index definition to use for checking match/equivalence
    /// </summary>
    /// <param name="index"></param>
    /// <param name="parent"></param>
    /// <returns></returns>
    public static string CanonicizeDdl(IndexDefinition index, Table parent)
    {
        var canonicizedStr = index.ToDDL(parent);
        return CanonicizeDdl(canonicizedStr, parent.Identifier.Schema);
    }

    public static string CanonicizeDdl(string sql, string schema)
    {
        // This was caused by https://github.com/JasperFx/marten/issues/2983
        sql = sql.Replace("if not exists", "", StringComparison.OrdinalIgnoreCase);
        sql = sql.Replace("desc nulls first", "desc", StringComparison.OrdinalIgnoreCase);
        sql = sql.Replace("asc nulls first", "asc", StringComparison.OrdinalIgnoreCase);
        sql = sql.Replace("TABLESPACE pg_default", "", StringComparison.OrdinalIgnoreCase);
        sql = sql.Replace("public.", "");
        sql = sql.Replace($"{schema}.", ""); //< --- remove schema anywhere it appears?
```

Let me know if you would like a pull request to fix this.

**Comment by mysticmind** [comment] 2024-03-20 05:26
I will look at this and sort it out, understand what the issue is at hand.

**Comment by mysticmind** [comment] 2024-03-20 06:19
Removing `public.` is a safe thing but not when you have a different namespace. It is a bit weird that Amazon RDS is returning you the SQL, most likely some bug with RDS which should be reported to them.

**Comment by bittercoder** [comment] 2024-03-20 07:48
Unfortunately I think the timeframe and likelyhood of Amazon addressing it is very low 😬 it feels like behavior that would be safe to "opt into" even if it wasn't the default, though that's a little more complex to then navigate between Marten and Weasel I would imagine.

**Comment by mysticmind** [comment] 2024-03-20 07:51
@bittercoder i am in principle okay with you proposed changes in PR. Let us roll on with it.

**Comment by bittercoder** [comment] 2024-03-20 08:05
Great thanks @mysticmind ✨

**Comment by bittercoder** [comment] 2024-03-20 08:05
Also if in the future we encounter unintended side effects for other users definitely let me know, I would be happy to work on something more opt-in so I can keep it working for RDS users 😁 without having the change backed out entirely.

**Comment by mysticmind** [comment] 2024-03-20 13:04
Your PR in Weasel is merged. When Weasel 7.3.0 is pulled in, this issue should get resolved.

**Comment by bittercoder** [comment] 2024-03-20 19:16
Awesome thanks so much!

**Closed** 2024-03-20 19:47 UTC
